theme: jekyll-theme-just-the-docs
title: "Study Archive"
description: "개인별 스터디 기록을 공유하고 함께 성장하는 공간"
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
show_downloads: false
markdown: kramdown
encoding: UTF-8
timezone: Asia/Seoul
github:
  is_project_page: false
  is_user_page: false
plugins:
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs