title: "Study Archive"
description: "개인별 스터디 기록을 공유하고 함께 성장하는 공간"
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
permalink: pretty
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
show_downloads: false
markdown: kramdown
encoding: UTF-8
timezone: Asia/Seoul
github:
  is_project_page: false
  is_user_page: false
  # 로컬 개발 시 GitHub Metadata 경고를 줄이기 위한 설정
  repository: "co-study/co-study.github.io"
plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jekyll-feed
title_from_headings:
  enabled: true
  strip_title: false
  collections: false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: "k"

# For copy button on code
enable_copy_code_button: true

nav_sort: case_sensitive # Capital letters sorted before lowercase

color_scheme: dark


nav_enabled: true
heading_anchors: true

# Remote theme 설정
remote_theme: just-the-docs/just-the-docs
remote_theme_branch: main

# just-the-docs 테마 navigation 설정
# nav_external_links:
#   - title: 카테고리
#     url: /category/
#   - title: Backend
#     url: /category/backend/
#   - title: Frontend
#     url: /category/frontend/
#   - title: DevOps
#     url: /category/devops/
#   - title: Algorithm
#     url: /category/algorithm/
#   - title: 기타
#     url: /category/etc/

# 포스트 기본 설정
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Unknown"
      category: "uncategorized"
  - scope:
      path: "category"
    values:
      layout: "category"
  - scope:
      path: ""
    values:
      layout: "default"
